from .cpl_kg import value_range
from collections import OrderedDict


Static_Simple = OrderedDict({
    "姓名名称" : value_range["字符串"],
    "是否变更诉讼请求" : value_range["是否"],

    "需返回本金总额（元）" : value_range["金额"],
    '需返回利息总额（元）' : value_range["金额"],
    '需返回利息计算起始日期' : value_range["日期值"],
    '需返回利息计算截止日期' : value_range["日期值"],
    '需返还利息率数值（百分比或元）' : value_range["率数值"],

    '需返回逾期利息总额（元）' : value_range["金额"],
    '需返回逾期利息计算起始日期' : value_range["日期值"],
    '需返回逾期利息计算截止日期' : value_range["日期值"],
    '需返还逾期利息率数值（百分比或元）' : value_range["率数值"],

    '需返回违约金总额（元）' : value_range["金额"],
    '需返回违约金计算起始日期' : value_range["日期值"],
    '需返回违约金计算截止日期' : value_range["日期值"],
    '需返还违约金数值（百分比或元）' : value_range["率数值"],

    '是否要求承担担保责任' : value_range["是否"],
    '承担保证责任的人或单位名称' : value_range["字符串"],
})


Static_Difficult = OrderedDict({
    "姓名名称" : value_range["字符串"],
    "是否变更诉讼请求" : value_range["是否"],

    "需返回本金总额（元）" : value_range["金额"],
    '需返回利息总额（元）' : value_range["金额"],
    '需返回利息计算起始日期' : value_range["日期值"],
    '需返回利息计算起始日期类型' : value_range["起始日期类型"],
    '需返回利息计算截止日期' : value_range["日期值"],
    '需返回利息计算截止日期类型' : value_range["截止日期类型"],
    '需返还利息率类型' : value_range["利率类型"],
    '需返还利息率数值（百分比或元）' : value_range["率数值"],
    '需返回逾期利息总额（元）' : value_range["金额"],
    '需返回逾期利息计算起始日期' : value_range["日期值"],
    '需返回逾期利息计算起始日期类型' : value_range["起始日期类型"],
    '需返回逾期利息计算截止日期' : value_range["日期值"],
    '需返回逾期利息计算截止日期类型' : value_range["截止日期类型"],
    '需返还逾期利息率类型' : value_range["利率类型"],
    '需返还逾期利息率数值（百分比或元）' : value_range["率数值"],
    '需返回违约金总额（元）' : value_range["金额"],
    '需返回违约金计算起始日期' : value_range["日期值"],
    '需返回违约金计算起始日期类型' : value_range["起始日期类型"],
    '需返回违约金计算截止日期' : value_range["日期值"],
    '需返回违约金计算截止日期类型' : value_range["截止日期类型"],
    '需返还违约金类型' : value_range["利率类型"],
    '需返还违约金数值（百分比或元）' : value_range["率数值"],
    '是否要求承担担保责任' : value_range["是否"],
    '承担保证责任的人或单位名称' : value_range["字符串"],
    '保证责任类型' : value_range["担保责任类型"],
    '需返回债权实现费用（起诉前）总额（元）' : value_range["金额"],
    '需返回债权实现费用（起诉前）类型' : value_range["费用类型"],
    '需返回债权实现费用（起诉后）总额（元）' : value_range["金额"],
    '需返回债权实现费用（起诉后）类型' : value_range["费用类型"],
    
    # 借贷事件
    # 借款事实信息
    "借款目的与用途类型" : value_range["借款用途"],
    "借款人与出借人关系类型" : value_range["借款人与出借人关系类型"],
    "担保人的姓名或单位名称" : value_range["字符串"],
    "借款人与担保人关系类型" : value_range["借款人与出借人关系类型"],
    "意思表示日" : value_range["日期值"],
    
    
    '管辖约定情况' : value_range["约定情况"],
    '仲裁约定情况' : value_range["约定情况"],
    '程序性费用的承担（律师费、诉讼费等）约定情况' : value_range["约定情况"],
    '约定程序性费用承担情况类型' : value_range["约定程序性费用承担情况类型"],
    
    # 特殊
    "法院对夫妻债务的认定": value_range["法院对夫妻债务的认定"],
    "法院对砍头息的认定" : value_range["法院对砍头息的认定"],
    "法院对公司为股东担保的效力的认定" : value_range["法院对公司为股东担保的效力的认定"],
    "债权取得类型" : value_range["债权取得类型"],
    "法院对主体资格与合同效力的认定" : value_range["法院对主体资格与合同效力的认定"],
    "法院对职业放贷人的认定" : value_range["法院对职业放贷人的认定"],
    "法院对是否属于互联网平台责任的认定" : value_range["是否"],
    "法院对民事案件的处理程序" : value_range["法院对民事案件的处理程序"],
})

Dynamic_Simple = OrderedDict({
    "姓名名称" : value_range["字符串"],
    "借款次数" : value_range["数值"],

    "是否有借款凭证" : value_range["是否"],
    '借款凭证1名称' : value_range["字符串"],
    '借款凭证1所载内容' : value_range["字符串"],
    '借款凭证2名称' : value_range["字符串"],
    '借款凭证2所载内容' : value_range["字符串"],
    '借款凭证3名称' : value_range["字符串"],
    '借款凭证3所载内容' : value_range["字符串"],

    # 约定
    '初始约定的借款金额情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的借款金额（元）' : value_range["金额"],
    '第2次约定的借款金额情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的借款金额（元）' : value_range["金额"],
    '第3次约定的借款金额情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的借款金额（元）' : value_range["金额"],

    '初始约定的还款日期或借款期限情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的还款日期' : value_range["日期值"],
    '第2次约定的还款日期或借款期限情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的还款日期' : value_range["日期值"],
    '第3次约定的还款日期或借款期限情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的还款日期' : value_range["日期值"],

    '初始约定的利息情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的利率数值（百分比或元）' : value_range["率数值"],
    '第2次约定的利息情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的利率数值（百分比或元）' : value_range["率数值"],
    '第3次约定的利息情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的利率数值（百分比或元）' : value_range["率数值"],

    '初始约定的逾期利息情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的逾期利率数值（百分比或元）' : value_range["率数值"],
    '第2次约定的逾期利息情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的逾期利率数值（百分比或元）' : value_range["率数值"],
    '第3次约定的逾期利息情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的逾期利率数值（百分比或元）' : value_range["率数值"],

    '初始约定的违约金情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的违约金数值（百分比或元）' : value_range["率数值"],
    '第2次约定的违约金情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的违约金数值（百分比或元）' : value_range["率数值"],
    '第3次约定的违约金情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的违约金数值（百分比或元）' : value_range["率数值"],
})

Dynamic = OrderedDict({
    "借款次数" : value_range["数值"],
    "借款次数情况" : value_range["借款次数情况"],
    # 约定事实信息
    "是否有借款凭证" : value_range["是否"],
    '借款凭证1名称' : value_range["字符串"],
    '借款凭证1类型' : value_range["借款凭证类型"],
    '借款凭证1出具时间' : value_range["日期值"],
    '借款凭证1所载内容' : value_range["字符串"],
    '借款凭证2名称' : value_range["字符串"],
    '借款凭证2类型' : value_range["借款凭证类型"],
    '借款凭证2出具时间' : value_range["日期值"],
    '借款凭证2所载内容' : value_range["字符串"],
    '借款凭证3名称' : value_range["字符串"],
    '借款凭证3类型' : value_range["借款凭证类型"],
    '借款凭证3出具时间' : value_range["日期值"],
    '借款凭证3所载内容' : value_range["字符串"],
    '初始约定的借款金额情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的借款金额（元）' : value_range["金额"],
    '第2次约定的借款金额情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的借款金额（元）' : value_range["金额"],
    '第3次约定的借款金额情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的借款金额（元）' : value_range["金额"],
    '初始约定的还款日期或借款期限情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的借款起始日期' : value_range["日期值"],
    '初始约定的还款日期' : value_range["日期值"],
    '初始约定的借款期限（月）' : value_range["数值"],
    '第2次约定的还款日期或借款期限情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的借款起始日期' : value_range["日期值"],
    '第2次约定的还款日期' : value_range["日期值"],
    '第2次约定的借款期限（月）' : value_range["数值"],
    '第3次约定的还款日期或借款期限情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的借款起始日期' : value_range["日期值"],
    '第3次约定的还款日期' : value_range["日期值"],
    '第3次约定的借款期限（月）' : value_range["数值"],
    '初始约定的利息情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的利率类型' : value_range["利率类型"],
    '初始约定的利率数值（百分比或元）' : value_range["率数值"],
    '第2次约定的利息情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的利率类型' : value_range["利率类型"],
    '第2次约定的利率数值（百分比或元）' : value_range["率数值"],
    '第3次约定的利息情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的利率类型' : value_range["利率类型"],
    '第3次约定的利率数值（百分比或元）' : value_range["率数值"],
    '初始约定的逾期利息情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的逾期利率类型' : value_range["利率类型"],
    '初始约定的逾期利率数值（百分比或元）' : value_range["率数值"],
    '第2次约定的逾期利息情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的逾期利率类型' : value_range["利率类型"],
    '第2次约定的逾期利率数值（百分比或元）' : value_range["率数值"],
    '第3次约定的逾期利息情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的逾期利率类型' : value_range["利率类型"],
    '第3次约定的逾期利率数值（百分比或元）' : value_range["率数值"],
    '初始约定的违约金情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的违约金类型' : value_range["利率类型"],
    '初始约定的违约金数值（百分比或元）' : value_range["率数值"],
    '第2次约定的违约金情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的违约金类型' : value_range["利率类型"],
    '第2次约定的违约金数值（百分比或元）' : value_range["率数值"],
    '第3次约定的违约金情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的违约金类型' : value_range["利率类型"],
    '第3次约定的违约金数值（百分比或元）' : value_range["率数值"],

    '初始约定的还款方式情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的本金还款方式' : value_range["约定还款方式类型"],
    '初始约定的利息还款方式' : value_range["约定还款方式类型"],
    '前述还款方式下每次还款总金额（元）' : value_range["金额"],
    '前述还款方式下每次还款日期' : value_range["日期值"],
    '第2次约定的还款方式情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的本金还款方式' : value_range["约定还款方式类型"],
    '第2次约定的利息还款方式' : value_range["约定还款方式类型"],
    '前述还款方式下每次还款总金额（元）' : value_range["金额"],
    '前述还款方式下每次还款日期' : value_range["日期值"],
    '第3次约定的还款方式情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的本金还款方式' : value_range["约定还款方式类型"],
    '第3次约定的利息还款方式' : value_range["约定还款方式类型"],
    '前述还款方式下每次还款总金额（元）' : value_range["金额"],
    '前述还款方式下每次还款日期' : value_range["日期值"],
    '初始约定的担保情况' : value_range["约定情况"],
    '初始约定的实际发生时间' : value_range["日期值"],
    '初始约定的担保方式类型' : value_range["担保方式类型"],
    '初始约定的担保范围' : value_range["字符串"],
    '初始约定的担保期限（月）' : value_range["金额"],
    '担保物当下状态' : value_range["字符串"],
    '初始约定的担保人类型' : value_range["担保人类型"],
    '初始约定的保证责任类型' : value_range["担保责任类型"],
    '第2次约定的担保情况' : value_range["约定情况"],
    '第2次约定的实际发生时间' : value_range["日期值"],
    '第2次约定的担保方式类型' : value_range["担保方式类型"],
    '第2次约定的担保范围' : value_range["字符串"],
    '第2次约定的担保期限（月）' : value_range["金额"],
    '担保物当下状态' : value_range["字符串"],
    '第2次约定的担保人类型' : value_range["担保人类型"],
    '第2次约定的保证责任类型' : value_range["担保责任类型"],
    '第3次约定的担保情况' : value_range["约定情况"],
    '第3次约定的实际发生时间' : value_range["日期值"],
    '第3次约定的担保方式类型' : value_range["担保方式类型"],
    '第3次约定的担保范围' : value_range["字符串"],
    '第3次约定的担保期限（月）' : value_range["金额"],
    '担保物当下状态' : value_range["字符串"],
    '第3次约定的担保人类型' : value_range["担保人类型"],
    '第3次约定的保证责任类型' : value_range["担保责任类型"],
    '借款实际交付金额1（元）' : value_range["金额"],
    '借款实际交付时间1' : value_range["日期值"],
    '借款实际交付方式类型1' : value_range["交付方式类型"],
    '借款实际交付1所对应的是第几笔借款' : value_range["数值"],
    '借款实际交付金额2（元）' : value_range["金额"],
    '借款实际交付时间2' : value_range["日期值"],
    '借款实际交付方式类型2' : value_range["交付方式类型"],
    '借款实际交付2所对应的是第几笔借款' : value_range["数值"],
    '借款实际交付金额3（元）' : value_range["金额"],
    '借款实际交付时间3' : value_range["日期值"],
    '借款实际交付方式类型3' : value_range["交付方式类型"],
    '借款实际交付3所对应的是第几笔借款' : value_range["数值"],
    '已还款总体情况类型' : value_range["已还款总体情况类型"],
    '已还款时间1' : value_range["日期值"],
    '已还款金额1（元）' : value_range["金额"],
    '已还款方式1' : value_range["交付方式类型"],
    '已还款金额性质1' : value_range["金额性质"],
    '已还款金额1所对应的是第几笔借款' : value_range["数值"],
    '已还款金额1所冲抵利息至哪一日' : value_range["日期值"],
    '已还款时间2' : value_range["日期值"],
    '已还款金额2（元）' : value_range["金额"],
    '已还款方式2' : value_range["交付方式类型"],
    '已还款金额性质2' : value_range["金额性质"],
    '已还款金额2所对应的是第几笔借款' : value_range["数值"],
    '已还款金额2所冲抵利息至哪一日' : value_range["日期值"],
    '已还款时间3' : value_range["日期值"],
    '已还款金额3（元）' : value_range["金额"],
    '已还款方式3' : value_range["交付方式类型"],
    '已还款金额性质3' : value_range["金额性质"],
    '已还款金额3所对应的是第几笔借款' : value_range["数值"],
    '已还款金额3所冲抵利息至哪一日' : value_range["日期值"],
})